name: 'Rust Cargo Deb Package Build (amd64, Ubuntu)'
description: 'Builds a .deb package, amd64, ubuntu'
branding:
  icon: 'package'
  color: 'orange'
inputs:
  cmd:
    description: 'build command'
    required: true
    default: 'cargo deb --target=x86_64-unknown-linux-musl'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.cmd }}
