name: 'Rust Cargo Deb Package Build (amd64, Ubuntu)'
description: 'Builds a .deb package, amd64, ubuntu'
branding:
  icon: 'package'
  color: 'orange'
runs:
  using: 'docker'
  image: 'docker://rincewindwizzard/rust-build-action:latest'

