name: 'Rust Cargo Deb Package Build (amd64, Ubuntu)'
description: 'Builds a .deb package, amd64, ubuntu'
branding:
  icon: 'package'
  color: 'orange'
inputs:
  gpg_private_key:
    description: 'GPG private key used for signing'
    required: true
  email:
    description: 'Email used for signing'
    required: true
runs:
  using: 'docker'
  image: 'docker://rincewindwizzard/rust-build-action:v13'

